/* This is autogenerated code. */

/* (generated Wed, 27 Aug 2014 15:22:36 +0200 by ladder-gen v 1.0) */

#ifndef LEDBLINKER_H
#define LEDBLINKER_H

#if ARDUINO >= 100
    #include "Arduino.h"   
#else
    #include "WProgram.h"
#endif

#define BOOL boolean
#define SWORD int

#define EXTERN_EVERYTHING
#define NO_PROTOTYPES

void PlcCycle(void);

/* Configure digital I/O according to LD (call this in setup()). */

inline void PlcSetup() {}


/* Individual pins (this code is used in ladder.cpp) */

inline extern BOOL Read_U_b_XD12(void)
{
  return 0;
    //return digitalRead(12);
}

inline BOOL Read_U_b_YD13(void)
{
  return false;
    //return digitalRead(13)!=0;
}

inline void Write_U_b_YD13(BOOL v)
{
    //digitalWrite(13, v);
}


#endif
